### ISSUE TITLE
Primary navigation 

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#435]
## What
A primary navigation bar for agent-facing services.

### Example: Move to UC

<img width="832" alt="Screen Shot 2021-02-17 at 09 59 26" src="https://user-images.githubusercontent.com/57486301/108187889-dc9dbe80-7106-11eb-83b6-2dc0a8c88b0c.png">

## Why
For agents to move between different features within a single service.

## Anything else

Initially set up for Bereavement Support Payment but this has been used on other internal services. 

The design was originally a grey bar with a solid teal background for selected items. The teal was found to fail the colour contrast ratio for WCAG-AA. The teal was then switched to govuk-blue. This tested ok, but then we needed a sub-nav (see screenshot).

The grey bar wouldn't work when embedded halfway down a page, so I looked around for existing designs. The style of nav I have chosen already exists on companies house and govuk-pay.

The navigation works fine both as the main nav and the sub-nav. Agents have no issues finding it and using it to navigate the site.

#### Research

- User type: Agents
- Accessibility: Tested on JAWS, Dragon, Zoomtext and Read&Write

#### Services

- Manage Bereavement Support Payment
- Access to work
- Support for Get your State Pension
- Manage a mortgage interest loan
- Move to Universal Credit

Appears in the GDS backlog - alphagov/govuk-design-system-backlog#76

### Code
<details>
<summary>HTML</summary>

```html
<nav class="navigation-global">
  <ul>
    <li>
      <a href="#" class="active" aria-current="page">Active link</a>
    </li>

    <li>
      <a href="#">Inactive Link</a>
    </li>

    <li>
      <a href="#">Another Link</a>
    </li>
  </ul>
</nav>
```
</details>
<details>
<summary>CSS</summary>

```CSS
#global-header-bar {
  display: none;
}

.navigation-global ul:after {
  content: "";
  display: block;
  clear: both;
}

.navigation-global {
  background: #dee0e2;
}

.navigation-global ul {
  margin: 0 auto;
  max-width: 960px;
}

.navigation-global li {
  float: left;
  list-style-type: none;
}

@media (max-width: 640px) {
  .navigation-global li {
    width: 100%;
  }
}

.navigation-global a {
  display: block;
  padding: 15px;
  text-decoration: none;
}

.navigation-global a:link,
.navigation-global a:visited {
  color: #0b0c0c;
}

.navigation-global a:active,
.navigation-global a:focus {
  background: #ffbf47;
  color: #0b0c0c;
}

.navigation-global a:hover {
  background: #f8f8f8;
  text-decoration: underline;
}

.navigation-global .active {
  background: #005ea5;
  border-bottom: 0;
  font-weight: 700;
}

.navigation-global .active:link,
.navigation-global .active:visited,
.navigation-global .active:active {
  color: #fff;
}

.navigation-global .active:focus {
  color: #0b0c0c;
}

.navigation-global .active:hover {
  background: #005ea5;
  color: #fff;
  text-decoration: underline;
} 
```
</details>

<details>
<summary>Sass</summary>

```SCSS
@import 'colours';
@import 'shims';

#global-header-bar {
  display: none;
}

.navigation-global {
  background: $panel-colour;

  ul {
    @extend %contain-floats;

    margin: 0 auto;
    max-width: 960px;
  }

  li {
    float: left;
    list-style-type: none;

    @include media(mobile) {
      width: 100%;
    }
  }

  a {
    display: block;
    padding: 15px;
    text-decoration: none;

    &:link,
    &:visited {
      color: $black;
    }

    &:active,
    &:focus {
      background: $focus-colour;
      color: $black;
    }

    &:hover {
      background: $highlight-colour;
      text-decoration: underline;
    }
  }

  .active {
    background: $govuk-blue;
    border-bottom: 0;
    font-weight: 700;

    &:link,
    &:visited,
    &:active {
      color: $white;
    }

    &:focus {
      color: $black;
    }

    &:hover {
      background: $govuk-blue;
      text-decoration: underline;
      color: $white;
    }
  }
}
```
</details>

### Sketch
[sketch.zip](https://github.com/dwp/design-system-community-backlog/files/6164475/sketch.zip)

**Original issue information:** 14 Dec 2017 @abbott567 https://github.com/dwp/design-system-community-backlog/issues/43
